---
title: "MNIST Guardar Train % Test de todos los números"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(survey)
library(sae)
library(TeachingSampling)
library(dplyr)
library(kableExtra)
library(knitr)
library(GGally)
library(survey)
library(TeachingSampling)
library(dplyr)
library(readxl)
library(rgeos)
library(sp)
library(gstat)
library(dplyr)
library(ggplot2)
library(devtools)
library(ggwithimages)
library(leaflet)
library(e1071) 
library(R.utils); library(dplyr)
source("fun.R")
options(scipen = 999)
```

##### Realizado por:

- **Nestor Jardany Serrano Rojas**, [GitHub](https://github.com/jardanys)

<br/>

## OBTENER MNIST

### Enlaces a los datasets
```{r mnist, echo=TRUE}
train_img_link <- "http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz"
train_labels_link <- "http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz"

test_img_link <- "http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz"
test_labels_link <- "http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz"
```

**Descarga información sólo si es necesario**

```{r descarga_informacion, echo=TRUE}
if(!file.exists("./MNIST")){
      dir.create("MNIST")
      
      ## Datasets imagenes
      download.file(url = train_img_link, destfile = "./MNIST/Train_img.gz")
      download.file(url = test_img_link, destfile = "./MNIST/Test_img.gz")
      
      ## labels datasets 
      download.file(url = train_labels_link, destfile = "./MNIST/Train_labels.gz")
      download.file(url = test_labels_link, destfile = "./MNIST/Test_labels.gz")
} else{
      if(!file.exists("./MNIST/Train_img.gz")) download.file(url = train_img_link, destfile = "./MNIST/Train_img.gz")
      if(!file.exists("./MNIST/Test_img.gz")) download.file(url = train_img_link, destfile = "./MNIST/Test_img.gz")
      if(!file.exists("./MNIST/Train_labels.gz")) download.file(url = train_img_link, destfile = "./MNIST/Train_labels.gz")
      if(!file.exists("./MNIST/Test_labels.gz")) download.file(url = train_img_link, destfile = "./MNIST/Test_labels.gz")
}
```

### cargue imagenes

```{r carga_imagenes, echo=TRUE}
train <- load_image_file("./MNIST/Train_img")
test  <- load_image_file("./MNIST/Test_img")
```

### Cargue labels

```{r cargue_label, echo=TRUE}
train$label = as.factor(load_label_file("./MNIST/Train_labels"))
test$label  = as.factor(load_label_file("./MNIST/Test_labels"))
```

### Ordenamos los datasets

```{r distancias_aeria, echo=TRUE}
train <- train %>% arrange(label)
test <- test %>% arrange(label)
```


### Train

```{r train, echo=TRUE}
id_train <- train %>%
            arrange(label) %>%
            mutate(id = 1:length(train$label)) %>%
            group_by(label) %>%
            summarise(fila_desde = min(as.numeric(id)), fila_hasta = max(as.numeric(id)))
```

### Test

```{r test, echo=TRUE}
id_test <- test %>%
           arrange(label) %>%
           mutate(id = 1:length(test$label)) %>%
           group_by(label) %>%
           summarise(fila_desde = min(as.numeric(id)), fila_hasta = max(as.numeric(id)))
id_test
```


## Gráfica de Números

```{r graficas, echo=TRUE}
show_digit(train[30598, ])
show_digit(test[5140, ])
```

## Guardar RDS de todos los números

```{r puntos_aeria, echo=TRUE}
if(!file.exists("./RDS")) {
      dir.create("RDS")
}

# train
for(i in 1:length(unique(train$label))){
      if(!file.exists(paste0("./RDS/Train_", i-1, ".rds"))) {
            saveRDS(filter(train, label==i-1), file = paste0("./RDS/Train_", i-1, ".rds"))
      }
}

# test
for(i in 1:length(unique(test$label))){
      if(!file.exists(paste0("./RDS/Test_", i-1, ".rds"))) {
            saveRDS(filter(test, label==i-1), file = paste0("./RDS/Test_", i-1, ".rds"))
      }
}
```



